[package]
name = 'libkrigingtemplate'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']

[dependencies]
anyhow = "1.0"
extendr-api = '0.6'
nalgebra = "0.32"
rand = "0.8"
rand_distr = "0.4"

[dev-dependencies]
rstest = "0.18"
