# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_libkrigingtemplate_wrappers", use_symbols = TRUE, package_name = "libkrigingtemplate")

#' @docType package
#' @usage NULL
#' @useDynLib libkrigingtemplate, .registration = TRUE
NULL

#' Return version string
#' @export
full_version <- function() .Call(wrap__full_version)

linear_regression_fit1 <- function(y, x) invisible(.Call(wrap__linear_regression_fit1, y, x))

linear_regression_fit2 <- function(y, x) invisible(.Call(wrap__linear_regression_fit2, y, x))

#' First linear regression implementation test
#' @export
LinearRegression <- new.env(parent = emptyenv())

LinearRegression$fit <- function(y, x) .Call(wrap__LinearRegression__fit, y, x)

LinearRegression$predict <- function(x) .Call(wrap__LinearRegression__predict, self, x)

#' @rdname LinearRegression
#' @usage NULL
#' @export
`$.LinearRegression` <- function (self, name) { func <- LinearRegression[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LinearRegression` <- `$.LinearRegression`


# nolint end
