name: R CMD check as CRAN

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * SAT'

env:
  PACKAGE_NAME: libkrigingtemplate

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r-version }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r-version: 'release' }
          - { os: macOS-latest,   r-version: 'release' }
          - { os: ubuntu-latest,  r-version: 'release' }
          - { os: ubuntu-latest,  r-version: 'devel', http-user-agent: 'release' }

    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r-version }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"never"'
